# Generated by Django 4.2.5 on 2023-09-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('temperature_value_celsius', models.FloatField()),
                ('temperature_value_fahrenheit', models.FloatField()),
                ('temperature_unit_celsius', models.CharField(max_length=1)),
                ('temperature_unit_fahrenheit',models.CharField(max_length=1)),
                ('weather_text', models.CharField(max_length=100)),
            ],
        ),
    ]
